package pkg:component;

interface intf {
    record request {
        message: string
    }
    record response {
        message: string
    }
    resource session {
        constructor();
        infer: func(prompt: request) -> response;
    }
    test: func(test: string) -> string;
    test2: func(test: string) -> future<string>;
    test3: func(test: future<string>) -> string;
    test4: func(test: stream<string>) -> stream<string>;
    test5: func();
    get-files: func() -> list<string>;
    read-file: func() -> string;
}

world guest {
    export intf;
}
